name: Ansible Lint
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.19.0
