name: Steampunk Spotter
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan Ansible content
        uses: xlab-steampunk/spotter-action@2.3.0
        with:
          paths: .
          ansible_version: 2.12
          display_level: warning
        env:
          SPOTTER_API_TOKEN: ${{ secrets.SPOTTER_API_TOKEN }}
